import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "@/wallet/WalletProvider";
import Nav from "@/components/nav/Nav";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "ChainSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col bg-emerald-600",
          GeistSans.className,
        )}
      >
        <WalletProvider>
          <Nav />
          {children}
          <Toaster />
        </WalletProvider>
      </body>
    </html>
  );
}
